### ISSUE TITLE
Add Contributing.md file 

### ISSUE THREAD

**Issue by ghost** [Sahiljawale/CodeChef#10]
I would like to add contributing.md file so that beginners can get the idea of hacktober fest and make this contribution easier.

**Comment by Sahiljawale** [comment]
Sure u can @Kdeveloper2000

**Comment by Rancho2002** [comment]
Hi @Sahiljawale , can you assign this to me? Its been a week since this issue is opened and contributing.md is necessary for a valid repo in hacktoberfest

**Comment by Rancho2002** [comment]
Hi @Sahiljawale , close this issue now
