### ISSUE TITLE
add one more problem of C++

### ISSUE THREAD

**Issue by Suryansh1720001** [Sahiljawale/CodeChef#13]
@Sahiljawale,
I want to add one more problem of C++. Assign this to me 
Thank you

**Comment by Purvesh77** [comment]
Hey @Suryansh1720001 I have added one problem "Chef_And_Board_Game" in C++ file 
Can You merge it ?
Thank You

**Comment by omi-sha** [comment]
hi! can i work on this issue?

**Comment by sahiljawale54** [comment]
> hi! can i work on this issue?

yes

**Comment by omi-sha** [comment]
i have added my code , thankyou
