### ISSUE TITLE
Add Yet Another Palindrome Problem Code

### ISSUE THREAD

**Issue by Nekros1712** [Sahiljawale/CodeChef#135]
https://www.codechef.com/submit/ARRPAL

**Comment by Nekros1712** [comment]
@Sahiljawale can you assign me here
I would like to provide neat and clean solution to this problem under hacktoberfest '22

**Comment by Yatiiii** [comment]
Can you please assign me this. As i'm a 5 star coder at codechef.Userhandle-(yati1103).

**Comment by Yatiiii** [comment]
Can i do it under hacktoberfest-2022?
