### ISSUE TITLE
Udpate links in redme.md

### ISSUE THREAD

**Issue by Sahiljawale** [Sahiljawale/CodeChef#7]

**Comment by Soumyajit2825** [comment]
@Sahiljawale assign this task to me
I want to add some more problems

**Comment by Ansh-Sarkar** [comment]
@Sahiljawale have fixed the links to point to this repo but I see that this issue has been assigned to @Soumyajit2825 . Should be opening a PR for this ?

**Comment by Soumyajit2825** [comment]
Pull Req done . PLease check and merge it if u find it helpful

**Comment by Ansh-Sarkar** [comment]
Have updated the links. Even @Soumyajit2825 were redirecting to his fork. Have updated them.

**Comment by Soumyajit2825** [comment]
good job

**Comment by ghost** [comment]
Hey, @Sahiljawale I want to add some more difficult level problems of good quality Questions.

**Comment by Purvesh77** [comment]
Hey @Sahiljawale I want to add Some problems 
Can You assign me ?

**Comment by sahiljarngal** [comment]
Hey, @Sahiljawale I solved so much problems in codechef and I want  to add solution . Can you assign me?

**Comment by Ruturaj-Panditrao** [comment]
Hi there, I would like to add some more problems which I find quite interesting & good !
